
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserRole = {
  ADMIN: 'ADMIN',
  USER: 'USER'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]


export const AuthProvider = {
  CLERK: 'CLERK'
} as const

export type AuthProvider = (typeof AuthProvider)[keyof typeof AuthProvider]


export const StripeAccountType = {
  EXPRESS: 'EXPRESS',
  STANDARD: 'STANDARD',
  CUSTOM: 'CUSTOM'
} as const

export type StripeAccountType = (typeof StripeAccountType)[keyof typeof StripeAccountType]


export const StripeAccountStatus = {
  NOT_CONNECTED: 'NOT_CONNECTED',
  PENDING: 'PENDING',
  ENABLED: 'ENABLED',
  RESTRICTED: 'RESTRICTED',
  REJECTED: 'REJECTED'
} as const

export type StripeAccountStatus = (typeof StripeAccountStatus)[keyof typeof StripeAccountStatus]


export const BlockType = {
  COMPONENT: 'COMPONENT',
  SECTION: 'SECTION',
  PAGE: 'PAGE'
} as const

export type BlockType = (typeof BlockType)[keyof typeof BlockType]


export const BlockFramework = {
  REACT: 'REACT',
  VUE: 'VUE',
  SVELTE: 'SVELTE'
} as const

export type BlockFramework = (typeof BlockFramework)[keyof typeof BlockFramework]


export const StylingEngine = {
  TAILWIND: 'TAILWIND',
  CSS: 'CSS'
} as const

export type StylingEngine = (typeof StylingEngine)[keyof typeof StylingEngine]


export const Visibility = {
  PRIVATE: 'PRIVATE',
  UNLISTED: 'UNLISTED',
  PUBLIC: 'PUBLIC'
} as const

export type Visibility = (typeof Visibility)[keyof typeof Visibility]


export const BlockStatus = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PUBLISHED: 'PUBLISHED',
  UNPUBLISHED: 'UNPUBLISHED',
  ARCHIVED: 'ARCHIVED'
} as const

export type BlockStatus = (typeof BlockStatus)[keyof typeof BlockStatus]


export const ModerationDecision = {
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  REQUEST_CHANGES: 'REQUEST_CHANGES'
} as const

export type ModerationDecision = (typeof ModerationDecision)[keyof typeof ModerationDecision]


export const RenderJobStatus = {
  QUEUED: 'QUEUED',
  RUNNING: 'RUNNING',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
  CANCELED: 'CANCELED'
} as const

export type RenderJobStatus = (typeof RenderJobStatus)[keyof typeof RenderJobStatus]


export const PreviewViewport = {
  MOBILE: 'MOBILE',
  TABLET: 'TABLET',
  DESKTOP: 'DESKTOP'
} as const

export type PreviewViewport = (typeof PreviewViewport)[keyof typeof PreviewViewport]


export const FileKind = {
  COMPONENT: 'COMPONENT',
  STYLE: 'STYLE',
  UTILS: 'UTILS',
  README: 'README',
  ASSET: 'ASSET',
  OTHER: 'OTHER'
} as const

export type FileKind = (typeof FileKind)[keyof typeof FileKind]


export const CodeStorageKind = {
  INLINE_ENCRYPTED: 'INLINE_ENCRYPTED',
  OBJECT_STORAGE: 'OBJECT_STORAGE'
} as const

export type CodeStorageKind = (typeof CodeStorageKind)[keyof typeof CodeStorageKind]


export const CurrencyCode = {
  USD: 'USD',
  EUR: 'EUR',
  CLP: 'CLP',
  GBP: 'GBP',
  MXN: 'MXN',
  ARS: 'ARS',
  BRL: 'BRL'
} as const

export type CurrencyCode = (typeof CurrencyCode)[keyof typeof CurrencyCode]


export const PurchaseStatus = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  CANCELED: 'CANCELED',
  REFUNDED: 'REFUNDED',
  CHARGEBACK: 'CHARGEBACK'
} as const

export type PurchaseStatus = (typeof PurchaseStatus)[keyof typeof PurchaseStatus]


export const DeliveryStatus = {
  NOT_READY: 'NOT_READY',
  READY: 'READY',
  REVOKED: 'REVOKED'
} as const

export type DeliveryStatus = (typeof DeliveryStatus)[keyof typeof DeliveryStatus]


export const LicenseType = {
  PERSONAL: 'PERSONAL',
  TEAM: 'TEAM',
  ENTERPRISE: 'ENTERPRISE'
} as const

export type LicenseType = (typeof LicenseType)[keyof typeof LicenseType]


export const LicenseStatus = {
  ACTIVE: 'ACTIVE',
  REVOKED: 'REVOKED'
} as const

export type LicenseStatus = (typeof LicenseStatus)[keyof typeof LicenseStatus]


export const RefundStatus = {
  NONE: 'NONE',
  REQUESTED: 'REQUESTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PROCESSED: 'PROCESSED'
} as const

export type RefundStatus = (typeof RefundStatus)[keyof typeof RefundStatus]


export const DisputeStatus = {
  OPEN: 'OPEN',
  NEEDS_RESPONSE: 'NEEDS_RESPONSE',
  UNDER_REVIEW: 'UNDER_REVIEW',
  WON: 'WON',
  LOST: 'LOST',
  CLOSED: 'CLOSED'
} as const

export type DisputeStatus = (typeof DisputeStatus)[keyof typeof DisputeStatus]


export const ReviewStatus = {
  VISIBLE: 'VISIBLE',
  HIDDEN: 'HIDDEN',
  REMOVED: 'REMOVED'
} as const

export type ReviewStatus = (typeof ReviewStatus)[keyof typeof ReviewStatus]


export const ApiKeyScope = {
  READ_PUBLIC: 'READ_PUBLIC',
  DOWNLOAD_PURCHASED: 'DOWNLOAD_PURCHASED',
  ADMIN: 'ADMIN'
} as const

export type ApiKeyScope = (typeof ApiKeyScope)[keyof typeof ApiKeyScope]


export const WebhookProvider = {
  STRIPE: 'STRIPE'
} as const

export type WebhookProvider = (typeof WebhookProvider)[keyof typeof WebhookProvider]


export const WebhookStatus = {
  RECEIVED: 'RECEIVED',
  PROCESSED: 'PROCESSED',
  FAILED: 'FAILED',
  IGNORED: 'IGNORED'
} as const

export type WebhookStatus = (typeof WebhookStatus)[keyof typeof WebhookStatus]


export const AuditActorType = {
  USER: 'USER',
  SYSTEM: 'SYSTEM'
} as const

export type AuditActorType = (typeof AuditActorType)[keyof typeof AuditActorType]


export const AuditAction = {
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  CREATOR_CONNECT_STRIPE: 'CREATOR_CONNECT_STRIPE',
  CREATOR_UPDATE_STRIPE: 'CREATOR_UPDATE_STRIPE',
  BLOCK_CREATE: 'BLOCK_CREATE',
  BLOCK_UPDATE: 'BLOCK_UPDATE',
  BLOCK_SUBMIT: 'BLOCK_SUBMIT',
  BLOCK_APPROVE: 'BLOCK_APPROVE',
  BLOCK_REJECT: 'BLOCK_REJECT',
  BLOCK_PUBLISH: 'BLOCK_PUBLISH',
  BLOCK_UNPUBLISH: 'BLOCK_UNPUBLISH',
  BLOCK_ARCHIVE: 'BLOCK_ARCHIVE',
  RENDERJOB_CREATE: 'RENDERJOB_CREATE',
  RENDERJOB_UPDATE: 'RENDERJOB_UPDATE',
  PURCHASE_CREATE: 'PURCHASE_CREATE',
  PURCHASE_PAID: 'PURCHASE_PAID',
  PURCHASE_FAILED: 'PURCHASE_FAILED',
  PURCHASE_REFUNDED: 'PURCHASE_REFUNDED',
  PURCHASE_CHARGEBACK: 'PURCHASE_CHARGEBACK',
  LICENSE_REVOKE: 'LICENSE_REVOKE',
  DOWNLOAD_CREATE: 'DOWNLOAD_CREATE',
  REVIEW_CREATE: 'REVIEW_CREATE',
  REVIEW_UPDATE: 'REVIEW_UPDATE',
  REVIEW_MODERATE: 'REVIEW_MODERATE',
  DISPUTE_CREATE: 'DISPUTE_CREATE',
  DISPUTE_UPDATE: 'DISPUTE_UPDATE',
  WEBHOOK_RECEIVED: 'WEBHOOK_RECEIVED',
  WEBHOOK_PROCESSED: 'WEBHOOK_PROCESSED',
  WEBHOOK_FAILED: 'WEBHOOK_FAILED'
} as const

export type AuditAction = (typeof AuditAction)[keyof typeof AuditAction]


export const PlanTier = {
  FREE: 'FREE',
  PRO: 'PRO',
  TEAM: 'TEAM',
  ENTERPRISE: 'ENTERPRISE'
} as const

export type PlanTier = (typeof PlanTier)[keyof typeof PlanTier]
